apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: claude-code-gitea-actions
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/timholm/claude-code-gitea-actions.git
    targetRevision: HEAD
    path: chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
