apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cmd-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/timholm/cmd-api.git
    targetRevision: HEAD
    path: chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
