apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "*"
    helm:
      valuesObject:
        persistence:
          enabled: true
          size: 5Gi
          storageClassName: local-path
        grafana.ini:
          server:
            root_url: https://holm.chat/grafana
            serve_from_sub_path: true
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring:80
                access: proxy
                isDefault: true
              - name: Loki
                type: loki
                url: http://loki.monitoring:3100
                access: proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
