apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "*"
    helm:
      valuesObject:
        persistence:
          enabled: true
          size: 5Gi
          storageClassName: local-path
        grafana.ini:
          server:
            root_url: https://holm.chat/grafana
            serve_from_sub_path: true
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring:80
                access: proxy
                isDefault: true
              - name: Loki
                type: loki
                uid: loki
                url: http://loki.monitoring:3100
                access: proxy
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: default
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
        dashboards:
          default:
            loki-logs:
              gnetId: 13639
              revision: 2
              datasource: Loki
            kubernetes-logs:
              gnetId: 15141
              revision: 1
              datasource: Loki
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
