apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "*"
    helm:
      valuesObject:
        adminPassword: holmgrafana
        env:
          GF_SECURITY_ADMIN_PASSWORD: holmgrafana
        persistence:
          enabled: true
          size: 5Gi
          storageClassName: local-path
        grafana.ini:
          server:
            domain: grafana.holm.chat
            root_url: https://grafana.holm.chat
          auth.anonymous:
            enabled: false
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://kube-prometheus-stack-prometheus.monitoring:9090
                access: proxy
                isDefault: true
              - name: Loki
                type: loki
                url: http://loki.monitoring:3100
                access: proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
