apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lenovo-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/timholm/cmd-api.git
    targetRevision: claude/cluster-logs-autodeploy-r3pb9
    path: lenovo-services
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
