apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "*"
    helm:
      valuesObject:
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          limits_config:
            retention_period: 168h
            reject_old_samples: true
            reject_old_samples_max_age: 168h
            query_timeout: 5m
            max_query_series: 5000
            max_entries_limit_per_query: 10000
            split_queries_by_interval: 15m
          querier:
            max_concurrent: 4
          query_range:
            parallelise_shardable_queries: false
          server:
            http_server_read_timeout: 5m
            http_server_write_timeout: 5m
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 10Gi
            storageClass: local-path
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
        gateway:
          enabled: false
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        test:
          enabled: false
        lokiCanary:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
