apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.twun.io
    chart: docker-registry
    targetRevision: "*"
    helm:
      valuesObject:
        image:
          repository: registry
          tag: "2"
        persistence:
          enabled: true
          size: 10Gi
        service:
          type: ClusterIP
          port: 5000
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  # Manual sync - observe only, don't auto-change
  syncPolicy: {}
