apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qnap-csi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/qnap-dev/QNAP-CSI-PlugIn.git
    targetRevision: HEAD
    path: Helm/trident
  destination:
    server: https://kubernetes.default.svc
    namespace: trident
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
