apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-iscsi
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-iscsi
  resources:
    requests:
      storage: 500Gi
