{{- if .Values.ollama.enabled }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ollama-external
  labels:
    app: ollama
    type: external
subsets:
  - addresses:
      - ip: {{ .Values.server.ip }}
    ports:
      - port: {{ .Values.ollama.port }}
        name: http
{{- end }}

{{- if .Values.bookforge.enabled }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: bookforge-external
  labels:
    app: bookforge
    type: external
subsets:
  - addresses:
      - ip: {{ .Values.server.ip }}
    ports:
      - port: {{ .Values.bookforge.port }}
        name: http
{{- end }}
