{{- if .Values.ollama.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ollama-route
  labels:
    app: ollama
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "ollama.holm.chat"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ollama-external
          port: {{ .Values.ollama.port }}
{{- end }}

{{- if .Values.bookforge.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bookforge-route
  labels:
    app: bookforge
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "bookforge.holm.chat"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: bookforge-external
          port: {{ .Values.bookforge.port }}
{{- end }}
